---
title: "Tools for Breaking a Vigenère Cipher"
output:
  html_document:
    toc: false
    df_print: paged
    theme: spacelab
---

## Assignment: due Sunday, 11:59 pm

0. Update your R package with this new version of [vigtools.R](../R/vigtools.R) and rebuild. This version contains several new functions and a template for the function `findVigKey`.

2. Complete the skeleton for the function `findVigKey` that consumes a ciphertext string `ciphertext` and a key length `keyLength`, and returns the key that produced the ciphertext, assuming that the ciphertext was produced using a Vigenère cipher with key length `keyLength`. Most/all of the code you need for this is in the slides, you just need to piece it together.  Test your `findVigKey` on the example provided in the skeleton documentation.

 3. Edit the `DESCRIPTION` file and update the version number to `0.1.1`. After you have built and reloaded your package, tested the examples, and checked the help files, click on `More` in the build menu, and build a source package. A new file called `cryptoXYZ_0.1.1.tar.gz` should appear in the parent directory. Upload this file to Canvas.
 
