---
title: "BCH Codes"
output:
  html_document:
    toc: false
    df_print: paged
    theme: spacelab
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = NA)
```

Upload to Canvas a PDF of your work for the following problems. 

## Assignment: due Monday 12/5, 11:59 pm

1. Use [Macaulay2](https://www.unimelb-macaulay2.cloud.edu.au/) for the following.
    a. Factor $x^{15}+1$ over $\mathbb{Z}_2$.
    b. For each factor $f_i(x)$ that you found in part (a), factor $f_i(x)$ over $\text{GF}(16)$. Write each factor in the form $(x+\alpha^j)$, where $\alpha$ is a primitive 15th root of unity.

2. Find generators for $[15,5]$ and $[15,10]$ BCH codes as follows.
    a. Find a polynomial $p(x)$ that generates a $[15,5]$ code in $\mathbb{Z}_2/(x^{15} + 1)$ with designed distance 7. Show that this code has the required designed distance by showing the factorization of $p(x)$ over $\text{GF}(16)$. 
    b. Find a polynomial $p(x)$ that generates a $[15,10]$ code in $\mathbb{Z}_2/(x^{15} + 1)$ with designed distance 4. Show that this code has the required designed distance by showing the factorization of $p(x)$ over $\text{GF}(16)$. 

3. The polynomial $g(x) = x^4 + x^3 + 1$ generates a BCH code in $\mathbb{Z}_2[x]/(x^{15}+1)$. Use the method given in the slides to correct the single error in the received word $r(x) = x^{14}+x^{13}+x^{10}+x^9+x^7+x^5+x+1$. Give the error vector, along with the corrected code word.

4. Let $\alpha$ be a primitive 15th root of unity in $\text{GF}(16)$. Find a generating polynomial for the distance 7 Reed-Solomon code in $\text{GF}(16)[x]/(x^{15}+1)$. Write your polynomial as the sum of terms of the form $\alpha^jx^k$, and give a generator matrix for the code whose nonzero entries all have the form $\alpha^j$.

5. Consider the code of Problem #4. Use the method given in the slides to correct the error in the following received word. 
$$r(x) = \alpha^{3}x^{14}+\alpha^{13}x^{13}+\alpha^{2}x^{12}+x^{11}+\alpha^{5}x^{10}+\alpha^{11}x^{9}+\alpha^{9}x^{8}+\alpha^{3}x^{6}+\alpha^{11}x^{5}+x^{4}+\alpha^{9}x^{3}+\alpha^{3}x^{2}+\alpha^{8}x+\alpha^{7}$$
Give the error vector, along with the corrected code word.
